language: csharp
solution: Twilio.sln
dist: trusty
sudo: required

install:
  - sudo apt-get install -y liblldb-3.6 liblttng-ust0 libunwind8
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-host-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-hostfxr-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-hostfxr-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sharedframework-ubuntu-x64.latest.deb
  - wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-sdk-ubuntu-x64.latest.deb
  - sudo dpkg -i dotnet-sdk-ubuntu-x64.latest.deb
  - dotnet restore Twilio.Tests/Twilio.Tests.csproj
  - dotnet build Twilio.Tests/Twilio.Tests.csproj

script:
  - dotnet run --project Twilio.Tests/Twilio.Tests.csproj
