language: csharp
solution: Twilio.sln
dist: xenial
sudo: required
mono: none
dotnet: 2.1

services:
  - docker

install:
  - dotnet restore
  - dotnet build --framework netstandard1.4 src/Twilio/Twilio.csproj
  - dotnet build --framework netstandard2.0 src/Twilio/Twilio.csproj
  - dotnet build --framework netcoreapp2.0 test/Twilio.Test/Twilio.Test.csproj

script:
  - dotnet run --framework netcoreapp2.0 --project test/Twilio.Test/Twilio.Test.csproj

deploy:
  provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true

notifications:
  slack:
    if: branch = master
    on_success: never
    on_failure: change
    rooms:
      - secure: VvnsqrTi9RKxxlZtOL3fAXlXCcKTGbXo6UrB9AGtYRx8xjFgwnKt+RONthbiYXr8auk8XbX5JKyyFB6Vzuc8zzu3a15BlXMtgaiPcRd2KKR4J8RzJbfNw2Ncx+M27mB+/8gXh+4XedjjsurXbJsNj2AUAz/oW4LPgjdURj/H6M0=
