version: '{build}'
image: Visual Studio 2017
configuration: Release
build_script:
- ps: . .\build.ps1
test: off
artifacts:
- path: .\Twilio.*.nupkg
branches:
  only:
    - main
deploy:
  provider: NuGet
  api_key:
    secure: VFvsLn6PF6HuLGwrGuXTuuRa8L4CjBmvPfwffdQdQ4oiKF3elGVtdiGY2JrEfTlw
  skip_symbols: false
  artifact: /Twilio\..*\.nupkg/
  on:
    branch: main
    APPVEYOR_REPO_TAG: true
